// src/components/molecules/radiobox.vue
<script setup lang="ts">
	import Radio from '../atoms/radio.vue';
	import Text from '../atoms/text.vue';

	const props = defineProps<{
		groupName: string;
		text: string;
		checked?: boolean;
		className?: string;
	}>();
</script>

<template>
	<fieldset
		:class="['inline-flex items-center gap-5xs flex-shrink', props.className]">
		<Radio :groupName="props.groupName" :checked="props.checked" />
		<Text tag="label" :text="props.text" />
	</fieldset>
</template>

// src/components/molecules/radiobox.tsx
import React from 'react';
import Radio from '@/components/atoms/radio';
import Text from '@/components/atoms/text';

interface Props {
	groupName: string;
	text: string;
	checked?: boolean;
	className?: string;
}

const Radiobox: React.FC<Props> = ({ groupName, text, checked, className }) => {
	return (
		<fieldset
			className={`inline-flex items-center gap-5xs flex-shrink ${className}`}>
			<Radio groupName={groupName} checked={checked} />
			<Text tag='label' text={text} />
		</fieldset>
	);
};

export default Radiobox;
