// src/components/molecules/step.vue
<script setup lang="ts">
	import Icon from '../atoms/icon.vue';
	import Text from '../atoms/text.vue';
	import Spacer from '../atoms/spacer.vue';

	const props = defineProps<{
		text: string;
		hasBar: boolean;
		done?: boolean;
		className?: string;
	}>();
</script>

<template>
	<li
		:class="[
			'flex items-center gap-5xs overflow-hidden whitespace-nowrap',
			props.className,
		]">
		<Icon
			name="check_circle"
			:filled="props.done"
			:className="props.done ? 'text-accent-500' : 'text-accent-900'" />

		<Text tag="label" :text="props.text" className="whitespace-nowrap" />

		<Spacer
			:direction="'horizontal'"
			:className="props.done ? 'bg-accent-500' : 'bg-accent-900'"
			v-if="props.hasBar" />
	</li>
</template>

<style scoped lang="scss">
	li {
		@apply w-full;
		width: -moz-available;
		width: -webkit-fill-available;
		width: stretch;

		&:last-of-type {
			@apply flex-shrink-0;
			@apply w-max;
		}
	}
</style>

// src/components/molecules/step.tsx
import React from 'react';
import Icon from '@/components/atoms/icon';
import Text from '@/components/atoms/text';
import Spacer from '@/components/atoms/spacer';

interface Props {
	text: string;
	hasBar: boolean;
	done?: boolean;
	className?: string;
}

const ListItem: React.FC<Props> = ({ text, hasBar, done, className }) => {
	return (
		<li
			className={`flex items-center gap-5xs overflow-hidden whitespace-nowrap ${className}`}>
			<Icon
				name='check_circle'
				filled={done}
				className={done ? 'text-accent-500' : 'text-accent-900'}
			/>

			<Text tag='label' text={text} className='whitespace-nowrap' />

			{hasBar && (
				<Spacer
					direction='horizontal'
					className={done ? 'bg-accent-500' : 'bg-accent-900'}
				/>
			)}
		</li>
	);
};

export default ListItem;
