// src/components/molecules/tag.tsx
import React from 'react';
import Icon from '@/components/atoms/icon';
import Text from '@/components/atoms/text';

interface Props {
	text: string;
	className?: string;
	leading_icon?: string;
	leading_icon_fill?: boolean;
	trailing_icon?: string;
	trailing_icon_fill?: boolean;
}

const Tag: React.FC<Props> = ({
	text,
	className,
	leading_icon,
	leading_icon_fill,
	trailing_icon,
	trailing_icon_fill,
}) => {
	return (
		<span
			className={`inline-flex items-center rounded-5xs px-xs py-5xs w-max bg-neutral-900 text-neutral-400 ${className}`}>
			{leading_icon && <Icon name={leading_icon} filled={leading_icon_fill} />}
			<Text tag='span' text={text} scale='xs' />
			{trailing_icon && (
				<Icon name={trailing_icon} filled={trailing_icon_fill} />
			)}
		</span>
	);
};

export default Tag;

// src/components/molecules/tag.vue
<script setup lang="ts">
	import Icon from '../atoms/icon.vue';
	import Text from '../atoms/text.vue';

	const props = defineProps<{
		text: string;

		className?: string;

		leading_icon?: string;
		leading_icon_fill?: boolean;

		trailing_icon?: string;
		trailing_icon_fill?: boolean;
	}>();
</script>

<template>
	<span
		:class="[
			'inline-flex items-center rounded-5xs px-xs py-5xs w-max bg-neutral-900 text-neutral-400',
			props.className,
		]">
		<Icon
			:name="props.leading_icon"
			:filled="leading_icon_fill"
			v-if="props.leading_icon" />
		<Text tag="span" :text="props.text" scale="xs" />
		<Icon
			:name="props.trailing_icon"
			:filled="trailing_icon_fill"
			v-if="props.trailing_icon" />
	</span>
</template>
