// src/components/molecules/toast.tsx
import React from 'react';
import Icon from '@/components/atoms/icon';
import Text from '@/components/atoms/text';

interface Props {
	text: string;
	className?: string;
}

const Toast: React.FC<Props> = ({ text, className }) => {
	return (
		<span
			className={`inline-flex items-center justify-center gap-5xs p-5xs rounded-5xs bg-amber-300 text-amber-950 max-w-full ${className}`}>
			<Icon name='warning' />
			<Text
				tag='span'
				text={text}
				className='whitespace-nowrap overflow-ellipsis overflow-hidden'
			/>
			<Icon name='close' />
		</span>
	);
};

export default Toast;

// src/components/molecules/toast.vue
<script setup lang="ts">
	import Icon from '../atoms/icon.vue';
	import Text from '../atoms/text.vue';

	const props = defineProps<{
		text: string;
		className?: string;
	}>();
</script>

<template>
	<span
		class="inline-flex items-center justify-center gap-5xs p-5xs rounded-5xs bg-amber-300 text-amber-950 max-w-full">
		<Icon name="warning" />
		<Text
			tag="span"
			:text="props.text"
			className="whitespace-nowrap overflow-ellipsis overflow-hidden" />
		<Icon name="close" />
	</span>
</template>
