// src/components/organisms/collapsible.vue
<script setup lang="ts">
	import Icon from '../atoms/icon.vue';
	import Text from '../atoms/text.vue';

	const props = defineProps<{
		text: string;
		className?: string;
		flat?: boolean;
		leading_icon?: string;
		leading_icon_filled?: boolean;
	}>();
</script>

<template>
	<details
		:class="[
			'w-full rounded-5xs overflow-hidden',
			props.flat ? '' : 'bg-neutral-900',
			props.className,
		]">
		<summary
			:class="[
				'flex items-center gap-5xs  w-full cursor-pointer ',
				props.flat ? '' : 'px-nm py-sm bg-neutral-800',
			]">
			<Icon
				:name="props.leading_icon"
				:filled="props.leading_icon_filled"
				v-if="props.leading_icon" />
			<Text tag="span" :text="props.text" className="w-full" />
			<Icon name="expand_more" />
		</summary>
		<ul class="flex flex-col gap-5xs p-5xs w-full">
			<slot />
		</ul>
	</details>
</template>

// src/components/organisms/collapsible.tsx
import React, { ReactNode } from 'react';
import Icon from '@/components/atoms/icon';
import Text from '@/components/atoms/text';

interface Props {
	text: string;
	className?: string;
	flat?: boolean;
	leading_icon?: string;
	leading_icon_filled?: boolean;
	children?: ReactNode;
}

const Collapsible: React.FC<Props> = ({
	text,
	className,
	flat,
	leading_icon,
	leading_icon_filled,
	children,
}) => {
	return (
		<details
			className={`w-full rounded-5xs overflow-hidden ${
				flat ? '' : 'bg-neutral-900'
			} ${className}`}>
			<summary
				className={`flex items-center gap-5xs w-full cursor-pointer ${
					flat ? '' : 'px-nm py-sm bg-neutral-800'
				}`}>
				{leading_icon && (
					<Icon name={leading_icon} filled={leading_icon_filled} />
				)}
				<Text tag='span' text={text} className='w-full' />
				<Icon name='expand_more' />
			</summary>
			<ul className='flex flex-col gap-5xs p-5xs w-full'>{children}</ul>
		</details>
	);
};

export default Collapsible;
