// src/components/organisms/list.tsx
import React, { ReactNode } from 'react';
import { allowedLists } from '@/commons/logic/atomicRules';

interface Props {
	tag: string;
	className?: string;
	children?: ReactNode;
}

const List: React.FC<Props> = ({ tag, className = '', children }) => {
	if (!allowedLists.includes(tag)) {
		throw new Error(`Invalid or unauthorized tag provided: ${tag}`);
	}

	return React.createElement(tag, { className: className }, children);
};

export default List;

// src/components/organisms/list.vue
<script setup lang="ts">
	import { allowedLists } from '@/commons/logic/atomicRules';

	const props = defineProps<{
		tag: string;
		className?: string;
	}>();

	if (!allowedLists.includes(props.tag)) {
		throw new Error(`Invalid or unauthorized tag provided: ${props.tag}`);
	}
</script>

<template>
	<component :is="props.tag" :class="[props.className]">
		<slot />
	</component>
</template>
