// src/components/organisms/stepper.tsx
import React from 'react';
import Step from '@/components/molecules/step';

interface Step {
	name: string;
	hasBar: boolean;
	done?: boolean;
}

interface StepListProps {
	steps: Step[];
	className?: string;
}

const StepList: React.FC<StepListProps> = ({ steps, className }) => {
	return (
		<ul
			className={`flex items-center flex-shrink justify-center whitespace-nowrap gap-5xs w-full ${className}`}>
			{steps.map((step, index) => (
				<Step
					key={index}
					text={step.name}
					hasBar={step.hasBar}
					done={step.done}
				/>
			))}
		</ul>
	);
};

export default StepList;

// src/components/organisms/stepper.vue
<script setup lang="ts">
	import Step from '../molecules/step.vue';

	const props = defineProps<{
		steps: Array<{
			name: string;
			hasBar: boolean;
			done?: boolean;
		}>;
		className?: string;
	}>();
</script>

<template>
	<ul
		:class="[
			'flex items-center flex-shrink justify-center whitespace-nowrap gap-5xs w-full',
			props.className,
		]">
		<Step
			:text="step.name"
			:hasBar="step.hasBar"
			:done="step.done"
			v-for="step in props.steps" />
	</ul>
</template>
