// src/components/organisms/tabs.tsx
import React from 'react';
import Button from '@/components/molecules/button';

interface Tab {
	active?: boolean;
	className?: string;
	leading_icon?: string;
	leading_icon_fill?: boolean;
	text?: string;
	trailing_icon?: string;
	trailing_icon_fill?: boolean;
}

interface TabsProps {
	variant?: string;
	tabs: Tab[];
	className?: string;
}

const Tabs: React.FC<TabsProps> = ({ variant, tabs, className }) => {
	return (
		<ul
			className={`inline-flex items-stretch overflow-x-auto overflow-y-hidden whitespace-nowrap max-w-full ${
				variant === 'rounded' ? 'rounded-5xl' : ''
			} ${className}`}>
			{tabs.map((tab, index) => (
				<Button
					key={index}
					text={tab.text}
					leading_icon={tab.leading_icon}
					leading_icon_fill={tab.leading_icon_fill}
					trailing_icon={tab.trailing_icon}
					trailing_icon_fill={tab.trailing_icon_fill}
					borderless
					flat
					className={`${variant === 'rounded' ? 'rounded-5xl' : ''} ${
						tab.active ? 'bg-accent-500 text-accent-900' : ''
					}`}
				/>
			))}
		</ul>
	);
};

export default Tabs;

// src/components/organisms/tabs.vue
<script setup lang="ts">
	import Button from '@/components/molecules/button.vue';

	const props = defineProps<{
		variant?: string;
		tabs: Array<{
			active?: boolean;
			className?: string;
			leading_icon?: string;
			leading_icon_fill?: boolean;
			text?: string;
			trailing_icon?: string;
			trailing_icon_fill?: boolean;
		}>;
		className?: string;
	}>();
</script>

<template>
	<ul
		:class="[
			'inline-flex items-stretch overflow-x-auto overflow-y-hidden whitespace-nowrap max-w-full',
			props.variant === 'rounded' ? 'rounded-5xl' : '',
		]">
		<Button
			:text="tab.text"
			:leading_icon="tab.leading_icon"
			:leading_icon_fill="tab.leading_icon_fill"
			:trailing_icon="tab.trailing_icon"
			:trailing_icon_fill="tab.trailing_icon_fill"
			borderless
			flat
			:class="[
				props.variant === 'rounded' ? 'rounded-5xl' : '',
				tab.active ? 'bg-accent-500 text-accent-900' : '',
			]"
			v-for="tab in props.tabs" />
	</ul>
</template>
